* Readme

CORS problem demonstration.

** Documentation

*** Nginx
https://nginx.org/en/docs/

*** CORS
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS
https://portswigger.net/web-security/cors

** Three projects
Let's create 3 simple Ruby on Rails projects: primary, secondary and apiary.
Then let's configure Nginx, so that the are accessed in the following way.

| server    | port | location   |
|-----------+------+------------|
| primary   |  443 | /          |
| secondary | 5010 | /secondary |
| apiary    | 5010 | /apiary    |


** Creating Projects

*** Creating Rails projects
Now we have 3 folders for the projects.

After creating gemset for the project and installing rails gem, I will create 3
projects.

#+begin_example
  rails new ./primary
  rails new ./secondary
  rails new ./apiary
#+end_example

*** Nginx

**** installations
On Ubuntu like sytem, Install it with:
#+begin_example
sudo apt install nginx
#+end_example

**** configuration
Go to folder: ~/etc/nginx/sites-enabled~
and remove the default configuration and create a link for the new one. Remember
that the path in the linking command will be different on your system.

#+begin_example
cd /etc/nginx/sites-enabled/
sudo rm -v ./default
sudo ln -s /home/jacek/Programming/Ruby/corsed_project/sites-available/corsed_project ./corsed_projec
#+end_example

Now, the folder should show the link
file:/etc/nginx/sites-enabled/

And, this should link to the configuration file
file:sites-available/corsed_project

**** test configuration

#+begin_example
$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
#+end_example

**** run it
#+begin_example
sudo nginx
sudo nginx -s reload
#+end_example

*** Modifying and running the Rails projects
Following the guides https://guides.rubyonrails.org/

**** generated 3 scaffolds
Then, ran the migrations and fixed routes.
[[file:primary/config/routes.rb::root]]
[[file:secondary/config/routes.rb::root]]
[[file:apiary/config/routes.rb::root]]

Now I have 3 projects to start experimenting

http://localhost:3000
http://localhost:3001
http://localhost:3002

Trying to access them via HTTPS

https://localhost
https://localhost:5010/secondary
https://localhost:5010/apiary

We have incorrect server config and problems with routes
