* Readme

CORS problem demonstration.

** Documentation

*** Nginx
https://nginx.org/en/docs/

*** CORS
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS
https://portswigger.net/web-security/cors

** Three projects
Let's create 3 simple Ruby on Rails projects: primary, secondary and apiary.
Then let's configure Nginx, so that the are accessed in the following way.

| server    | port | location   |
|-----------+------+------------|
| primary   |  443 | /          |
| secondary | 5010 | /secondary |
| apiary    | 5010 | /apiary    |

** Creating Projects
*** Creating Rails projects
Now we have 3 folders for the projects.

After creating gemset for the project and installing rails gem, I will create 3
projects.

#+begin_example
  rails new ./primary
  rails new ./secondary
  rails new ./apiary
#+end_example

*** Nginx

**** installations
On Ubuntu like sytem, Install it with:
#+begin_example
sudo apt install nginx
#+end_example

**** configuration
Go to folder: ~/etc/nginx/sites-enabled~
and remove the default configuration and create a link for the new one. Remember
that the path in the linking command will be different on your system.

#+begin_example
cd /etc/nginx/sites-enabled/
sudo rm -v ./default
sudo ln -s /home/jacek/Programming/Ruby/corsed_project/sites-available/corsed_project ./corsed_projec
#+end_example

Now, the folder should show the link
file:/etc/nginx/sites-enabled/

And, this should link to the configuration file
file:./sites-available/corsed_project

**** test configuration

#+begin_example
$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
#+end_example

**** run it
#+begin_example
sudo nginx
sudo nginx -s reload
#+end_example

*** Modifying and running the Rails projects
Following the guides https://guides.rubyonrails.org/

**** generated 3 folders with rails projects
I used gemset
file:.rbenv-gemsets
and installed the gems

**** generated 3 scaffolds
Then, ran the migrations and fixed routes.
[[file:primary/config/routes.rb::root]]
[[file:secondary/config/routes.rb::root]]
[[file:apiary/config/routes.rb::root]]

Now I have 3 projects to start experimenting

http://localhost:3000

http://localhost:3001

http://localhost:3002

Trying to access them via HTTPS

https://localhost

https://localhost:5010/secondary

https://localhost:5010/apiary

The services on port 5010 will be accessible with their respective
prefixes, like apiary, but rails routes will no see them.

For example https://localhost:5010/apiary/foo will be seen by rails as
http://127.0.0.1:3002/foo

** Replicating the problem
*** The goal
On primary service
http://localhost:3000 or https://localhost
create a JavaScript that uses an api service on the apiary

https://localhost:5010/apiary/api/v1/hello

**** API routes and controllers
file:apiary/config/routes.rb

will give the route:
#+begin_example
api_v1_hello GET    /api/v1/hello(.:format)   api/v1/hellos#show
#+end_example

file:apiary/app/controllers/api/v1/hellos_controller.rb

**** Elm widget
Now we need a simple Elm widget that will talk to the API to greet us with
current time.

Now we have the beginning of a project, and the script that will compile our simple example
file:primary/vendor/elm/hello/compile_widget.sh

Now let's show that widget somewhere
file:primary/app/views/primary_names/index.html.erb

*** CORS errors
At this point I can not load the hello with error on the primary app in the browser's JS console.
#+begin_example
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:5010/apiary/api/v1/hello. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
#+end_example

**** not allowed cheating solution
https://medium.com/@guylikericky/how-to-solve-cors-error-on-ruby-on-rails-as-an-api-b497c4a32fcc

With not allowed asterisk origins
file:./apiary/config/initializers/cors.rb
I was able to load the resource.
#+begin_example
    origins '*'
#+end_example

Changing origins to
#+begin_example
    origins 'https://localhost'
#+end_example
also works.

**** trying two origins
file:./apiary/config/initializers/cors.rb::1

trying http://localhost:3000 or https://localhost -

the syntax for both is below, NOTE separate strings, separated by commas, so it
is not one string separated by commas
#+begin_example
origins 'https://localhost', 'http://localhost:3000'
#+end_example

When I comment out one of the origins
#+begin_example
    origins 'https://localhost' #, 'http://localhost:3000'
#+end_example
then http://localhost:3000 no longer works

**** trying many origins
Many correct origins may work, but I did not test it with the secondary app
#+begin_example
origins 'https://localhost', 'http://localhost:3000',  'http://localhost:3001'
#+end_example

**** trying 2 different origins

***** primary
this on works fine, no console errors
https://localhost

this one woks fine
http://localhost:3000

***** secondary
this one does not work with weird browser console errors
https://localhost:5010/secondary

this one works fine
http://localhost:3001

** 2 Questions
1- So is it a matter of finding the attempted origins in the browser and adding the
to the list with the correct syntax?

2- Could server configuration error be a problem?
